# Managed by DavidVeksler/dependabot-fleet
version: 2

updates:
  - package-ecosystem: "nuget"
    directories:
      - "/"
      - "/CodeContext.Tests"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "01:25"
      timezone: "America/Denver"
    open-pull-requests-limit: 5
    groups:
      non-major-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "02:45"
      timezone: "America/Denver"
    open-pull-requests-limit: 5
    groups:
      non-major-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
